# Generated by Django 3.2.8 on 2021-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='second',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
