# Generated by Django 3.2.8 on 2021-12-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0003_auto_20211209_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='previous_time_minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='previous_time_second',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
