# Generated by Django 3.2.8 on 2021-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_alter_topic_given_time_in_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='given_time_in_minute',
            field=models.PositiveIntegerField(verbose_name='given time'),
        ),
    ]
