# Generated by Django 3.2.8 on 2021-12-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_alter_topic_given_time_in_minute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
